import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { debounceTime, distinctUntilChanged, map } from 'rxjs/operators';
import { Observable } from 'rxjs';
import { CovidService } from '../common/services/covid.service';
import * as xlsx from 'xlsx';
@Component({
  selector: 'app-reportes',
  templateUrl: './reportes.component.html',
  styleUrls: ['./reportes.component.scss']
})
export class ReportesComponent implements OnInit {
  @ViewChild('epltable', { static: false }) epltable: ElementRef;
  data: any = {
    depto: null,
    date: null,
    type: null,
    line: null
  }
  areas = [
    ' (AiP/LOG)',
    '(AiP/MSE-TS)',
    '(ED/EAC3.1-TS-NA)',
    '(ED/SAL-TS-NA)',
    '(ED/SOE-PJM-NA)',
    '(ED/SPM-TS-Ai)',
    '(ED/SPM-TS-NA BMSN)',
    '(ED/SPM-TS-NA)',
    'AA/HRD',
    'ATMO-7MX/CTG',
    'ATMO-7MX/EDM',
    'ATMO-7MX/EDM1',
    'ATMO-7MX/EDM2',
    'ATMO-7MX/EES',
    'ATMO-7MX/EES1',
    'ATMO-7MX/EES2',
    'ATMO-7MX/MAT',
    'ATMO-7MX/MAT1',
    'ATMO-7MX/MAT2',
    'ATMO-7MX/MOE',
    'ATMO-7MX/MOE10',
    'ATMO-7MX/MOE20',
    'ATMO-7MX/MOE30',
    'ATMO-7MX/PJ-CS',
    'ATMO-7MX/PJ-CS2',
    'ATMO-7MX/PJM',
    'ATMO-7MX/QMM',
    'ATMO-7MX/SGS',
    'ATMO-7MX/SPE',
    'ATMO-7MX/TCR',
    'C/FIO1-MX',
    'C/FIO-MX_a-Tl',
    'C/HRR5-MX',
    'C/HRR6.2-MX',
    'C/TES2-NA_a-TlP',
    'C/TXR-MX-B',
    'C/TXR-MX-F_a-Tl',
    'CF/ACC1-MX',
    'CI/CWR21-MX',
    'CI/CWR2-MX_a-Tl',
    'CP/ABW56',
    'CP/PPE-MX',
    'CP/PUI13-MX_a-Tl',
    'CP/PUQ1-MX',
    'ED/EAC11-CA-NA',
    'ED/EAC1-CA-NA',
    'ED/EAC1-PA-NA',
    'ED/EAC1-TS-Tl',
    'ED/EAC2.1-WS-NA',
    'ED/EAC2.2-WS-NA',
    'ED/EAC21-CA-NA',
    'ED/EAC22-CA-NA',
    'ED/EAC23-CA-NA',
    'ED/EAC24-CA-NA',
    'ED/EAC2-CA-NA',
    'ED/EAC2-TS-Tl',
    'ED/EAC2-WS-NA',
    'ED/EAC3-TS-NA',
    'ED/EAC3-TS-Tl',
    'ED/EAC-CA-PA-NA',
    'ED/ECP1-Tl',
    'ED/ECP3-Tl',
    'ED/ECP-Tl',
    'ED/EEF1-TS-Tl',
    'ED/ENG-Tl',
    'ED/ENG-TS-TL',
    'ED/ESM1-Tl',
    'ED/ESM2-Tl',
    'ED/ESM-Tl',
    'ED/ESY-Tl',
    'ED/EVR-CA-Tl',
    'ED/EVR-PA-Tl',
    'ED/EVR-PA-Tl_a-472',
    'ED/EVR-PA-TL_A-566',
    'ED/EVR-Tl',
    'ED/EVR-TS-Tl',
    'ED/EVR-TS-Tl_a-472',
    'ED/EVR-WS-Tl',
    'ED/EVR-WS-Tl_a-472',
    'ED/HRD',
    'ED/HRM-AM',
    'ED/PJ-EPR',
    'ED/PJ-LM',
    'ED/PJ-LM-TLP',
    'ED/QMM1234-LAB-TL',
    'ED/QMM1234-TL',
    'ED/QMM1-TL',
    'ED/QMM24-Tl',
    'ED/QMM3-TL',
    'ED/QMM-Tl',
    'ED/RBU-TS-NA',
    'ED/SPJ21-CAPA-NA',
    'ED/SPJ2-CAPA-NA',
    'ED/SPM-TS-NA',
    'ED/SPM-TS-TlP',
    'ED/SPM-WS-NA',
    'ED-TS/EEF2-Tl',
    'ESY',
    'EVR',
    'FCM1-Tl',
    'FCM2-Tl',
    'FCM3-Tl',
    'FCM4-Tl',
    'FCM-Tl',
    'GS/ACC11-MX',
    'GS/ACC1-MX',
    'GS/ACC21-MX_a-Tl',
    'GS/ACC31-MX',
    'GS/ACC411-MX',
    'GS/ACC41-MX',
    'GS/ACC44-MX',
    'GS/ACC45-MX',
    'GS/ACC4-MX',
    'GS/ACC5-MX_a-TlP',
    'GS/ACC-MX',
    'GS/CTM-NA_a-TL',
    'GS/CTS4-NA_a-Tl',
    'GS/DSS3-NA_a-Tl',
    'GS/DSS4-NA_a-TI',
    'GS/GOI5.1-AM',
    'GS/HRS7-MX_a-Tl',
    'GS/LOD-MX',
    'GS/LOF1-NA',
    'GS/LOF2-TlP',
    'GS/LOF3-TlP',
    'GS/LOF4-NA',
    'GS/LOF-MX',
    'GS/LOT-NA2_a-TlP',
    'GS/MAC-AM_a-MX',
    'GS/PEQ1-MX',
    'GS/PER1-NA',
    'GS/PER2.2-MX',
    'GS/PER2.3-MX',
    'GS/PER2.4-MX',
    'GS/PER2-MX',
    'GS/PER-NA',
    'GS/PJ-DIA-AM_a-Tlp',
    'GS/POI4-AM1_a-Tl',
    'GS/PUI4-AM1_a-TlP',
    'GS/PUI6-AM1_a-TlP',
    'GS/PUI6-SC_a-Tlp',
    'GS/RMP12.2-MX_a-TlP',
    'GS/TEC2-AM_a-MX',
    'M/PDW25_a-Tl',
    'M/PDW35_a-Tl',
    'M/PDW46',
    'M/PDW46.1',
    'M/PDW56',
    'M/PDW86',
    'M/PDW86.1',
    'M/PII-AM2',
    'M/PMQ6.1-ED',
    'M/PMQ6.2-ED',
    'M/PMQ6-ED',
    'M/PMQ6-PC1_a-Tlp',
    'M/PPE1_a-Tl',
    'M/PPE-CA61',
    'M/PPE-CA62',
    'M/PPE-MX',
    'M/PPE-PA6',
    'M/PPE-TS6',
    'M/PPE-WS6',
    'M/PPP22-MX',
    'M/PPS-FS3',
    'M/PPS-SD2_a-Mx',
    'M/PPS-TC3',
    'M/PPS-TC3-D',
    'M/PQA1.1-TlP',
    'M/PQA1.2-TlP',
    'M/PQA2.1-TlP',
    'M/PQA2.2-TlP',
    'M/PQA2.2-TlP_a',
    'M/PQA2-TlP',
    'M/PQA-TlP',
    'M/PQT10-NA2_a-TlP',
    'M/PQT2-NA2',
    'M/PQT35-NA1_a-TlP',
    'M/PQT48-NA1_a-TlP',
    'M/PQT9.1-NA',
    'M/PQT-NA1',
    'M/PSD-MX',
    'M/PSD-MX1',
    'MexP/HRL',
    'MexP/HRL3',
    'PS/ENG1.11-ES-MX',
    'PS/ENG1.1-ES-MX',
    'PS/ENG1-ES-NA',
    'PS/HRD',
    'PS-FS/ENG3-MX',
    'PS-FS/ENG3-MX_a-951',
    'PS-FS/PJM1-MX',
    'PS-FS/PJM-MX',
    'PS-SD/EPS6',
    'PS-TC/ENS1-MX_a-Tl',
    'PS-TC/PJ-Tl',
    'PT/HRM',
    'RBEI/EBS1.1.2-MX_a-TL',
    'RBEI/EBS1.1.3-MX_a-TL11',
    'RBEI/EBS1.4-MX_a-TlP',
    'RBEI/EBS2.1.5-MX_a-TL11',
    'RBEI/EBS2.1.6-MX_a-TL11',
    'RBMX/HRC',
    'RBMX/HSE4-TlP',
    'RBMX/PRS1',
    'RBMX/PSO1',
    'RBMX/TLP',
    'RBNA/ISP-SVC2-MX_a-TlP',
    'SP',
    'TLP/BPS',
    'TlP/COM',
    'TlP/COR',
    'TlP/CTG',
    'TLP/CTG_A-100',
    'TlP/CTG1',
    'TlP/CTG11',
    'TlP/CTG12',
    'TlP/CTG13',
    'TlP/CTG2',
    'TlP/CTG21',
    'TLP/ENG-AA',
    'TlP/FCM2',
    'TLP/HRL',
    'TlP/HRL1',
    'TLP/HRL11',
    'TlP/HRL2',
    'TLP/HRL21',
    'TLP/HRL211',
    'TLP/HRL3',
    'TlP/ICO',
    'TlP/LOC1',
    'TlP/LOC2',
    'TlP/LOC3',
    'TLP/LOG',
    'TLP/LOG-Q1',
    'TLP/LOG-Q2',
    'TlP/LOI',
    'TlP/LOI1',
    'TlP/LOP',
    'TLP/LOP2',
    'TlP/LOP2_a-116',
    'TlP/LOP21',
    'TLP/LOP22',
    'TlP/LOP23',
    'TlP/LOP24',
    'TlP/LOP3',
    'TlP/LOP4',
    'TlP/LOP5',
    'TlP/LOP-AA',
    'TlP/LOT',
    'TLP/LOW',
    'TlP/LOW-AMD1',
    'TlP/LOW-AMD13',
    'TlP/LOW-AMD2',
    'TLP/LOW-AMD21',
    'TlP/LOW-AMD22',
    'TlP/LOW-AMD23',
    'TlP/LOW-AMD3',
    'TLP/LOW-APE',
    'TlP/LOW-APE1',
    'TLP/LOW-APE2',
    'TlP/LOW-APE3',
    'TlP/LOW-AUD',
    'TLP/LOW-RMA',
    'TlP/LOW-RMA1',
    'TlP/LOW-RMA2',
    'TlP/LOW-RMA3',
    'TLP/MFC-BPS',
    'TlP/MFO-AA',
    'TlP/MFO-CA1',
    'TlP/MFO-CA2',
    'TlP/MFO-CA21',
    'TlP/MFO-CA3',
    'TlP/MFO-CO',
    'TlP/MFO-CO1',
    'TlP/MFO-FS',
    'TLP/MFO-FS1',
    'TlP/MFO-FS-M',
    'TlP/MFO-LPS',
    'TlP/MFO-LPS1',
    'TlP/MFO-PA',
    'TlP/MFO-PA1',
    'TlP/MFO-PA2',
    'TlP/MFO-SH',
    'TlP/MFO-TC2',
    'TlP/MFO-TC3',
    'TlP/MFO-TS1',
    'TlP/MFO-TS4',
    'TlP/MFO-TS41',
    'TlP/MFO-TS42',
    'TlP/MFO-TS43',
    'TlP/MFO-TS44',
    'TlP/MFO-TS45',
    'TlP/MFO-TS46',
    'TlP/MFO-TS47',
    'TlP/MFO-TS5',
    'TlP/MFO-TS-M1',
    'TlP/MFO-TS-M2',
    'TlP/MFO-WS',
    'TLP/MFQ2',
    'TlP/MFQ-CA41',
    'TlP/MFQ-CA42',
    'TlP/MFQ-CA43',
    'TLP/MFQ-CO',
    'TLP/MFQ-FS2',
    'TlP/MFQ-FS-LPS',
    'TlP/MFQ-LPS',
    'TLP/MFQ-PA',
    'TLP/MFQ-SH',
    'TlP/MFQ-TS1',
    'TlP/MFQ-TS2',
    'TlP/MFQ-TS3',
    'TLP/MFQ-TS4',
    'TlP/MFQ-TS5',
    'TLP/MFQ-WS',
    'TlP/MFQ-WS-AA',
    'TlP/MFT-TEF6',
    'TlP/MSE-AA',
    'TLP/MSE-AT',
    'TLP/MSE-CA',
    'TlP/MSE-CA1',
    'TlP/MSE-CA11',
    'TLP/MSE-CA2',
    'TlP/MSE-CA3',
    'TlP/MSE-CA4',
    'TlP/MSE-CA5',
    'TlP/MSE-CA-M',
    'TlP/MSE-CA-M1',
    'TlP/MSE-CA-M2',
    'TLP/MSE-CO',
    'TlP/MSE-CO1',
    'TLP/MSE-CO-M',
    'TlP/MSE-FS',
    'TlP/MSE-FS-LPS1',
    'TLP/MSE-FS-LPS12',
    'TlP/MSE-FS-M',
    'TlP/MSE-HRL',
    'TlP/MSE-LPS',
    'TlP/MSE-LPS-M',
    'TLP/MSE-PA',
    'TLP/MSE-PA1',
    'TlP/MSE-PA2',
    'TLP/MSE-PA-M',
    'TLP/MSE-PS',
    'TLP/MSE-SH',
    'TLP/MSE-SH-M',
    'TlP/MSE-TC',
    'TlP/MSE-TC1',
    'TlP/MSE-TC11',
    'TLP/MSE-TC2',
    'TLP/MSE-TC21',
    'TLP/MSE-TC4',
    'TLP/MSE-TC-M',
    'TLP/MSE-TS',
    'TlP/MSE-TS1',
    'TLP/MSE-TS2',
    'TLP/MSE-TS3',
    'TlP/MSE-TS4',
    'TlP/MSE-TS5',
    'TLP/MSE-TS-M',
    'TLP/MSE-WS',
    'TLP/MSE-WS1',
    'TlP/MSE-WS2',
    'TLP/MSE-WS3',
    'TLP/MSE-WS4',
    'TLP/MSE-WS-M',
    'TlP/MSE-WS-M1',
    'TLP/OFE',
    'TlP/PJ-CTG',
    'TlP/PJ-FS-LPS',
    'TLP/PJ-LOG',
    'TlP/PJ-QM',
    'TlP/PJ-TC',
    'TlP/PM',
    'TLP/PMO',
    'TlP/QMM-CA',
    'TlP/QMM-ED1',
    'TlP/QMM-LAB',
    'TlP/QMM-LAB1',
    'TLP/QMM-LAB2',
    'TlP/QMM-LAB3',
    'TlP/QMM-LAB4',
    'TlP/QMM-LAB-CA-PA',
    'TlP/QMM-PS',
    'TLP/QMM-PS1',
    'TLP/QMM-PS2',
    'TlP/QMM-PS3',
    'TLP/QMM-QS',
    'TlP/QMM-QS1',
    'TLP/TEF',
    'TLP/TEF1',
    'TlP/TEF13',
    'TLP/TEF2',
    'TlP/TEF22',
    'TlP/TEF23',
    'TlP/TEF4',
    'TlP/TEF7'
  ]
  lines = [
    'N/A',
    'L-001/ CC001',
    'L-037/ CC070',
    'L-038/ CC038',
    'L-039/ CC071',
    'L-055/ CC040',
    'L-072/ CC407',
    'L-073/ CC408',
    'L-075/ CC075',
    'L-077/ CC077',
    'L-083/ CC083',
    'L-091/ CC412',
    'L-129 / CC129',
    'L-176/ CC176',
    'L-185/ CC185',
    'L-246/ CC246',
    'L-279/ CC750',
    'L-304/ CC418',
    'L-306/ CC420',
    'L-307/ CC421',
    'L-329/ CC072',
    'L-366/ CC366',
    'L-405/ CC405',
    'L-410/ CC410',
    'L-413/ CC413',
    'L-464/ CC464',
    'L-465/ CC465',
    'L-528/ CC042',
    'L-591/ CC044',
    'L-593/ CC046',
    'L-593/ CC593',
    'L-595/ CC048',
    'L-610/ CC073',
    'L-612/ CC030',
    'L-624 / CC624',
    'L-631/ CC631',
    'L-634/ CC000',
    'L-641/ CC002',
    'L-648/ CC006',
    'L-656 / CC656',
    'L-658/ CC007',
    'L-660/ CC049',
    'L-661/ CC050',
    'L-666/ CC041',
    'L-672/ CC074',
    'L-673/ CC082',
    'L-683/ CC033',
    'L-685/ CC055',
    'L-686/ CC056',
    'L-687/ CC056',
    'L-689/ CC034',
    'L-690/ CC057',
    'L-698/ CC008',
    'L-699/ CC009',
    'L-703/ CC035',
    'L-708/ CC076',
    'L-710/ CC060',
    'L-712/ CC012',
    'L-713/ CC013',
    'L-716/ CC016',
    'L-717/ CC017',
    'L-718/ CC018',
    'L-723/ CC020',
    'L-726/ CC759',
    'L-737/ CC078',
    'L-740A/ CC080',
    'L-740B/ CC080',
    'L-741/ CC761',
    'L-744/ CC762',
    'L-746/ CC021',
    'L-751/ CC751',
    'L-752/ CC752',
    'L-753/ CC753',
    'L-753B/ CC753',
    'L-754/ CC754',
    'L-754SUBENSAMBLES/ CC754',
    'L-755/ CC755',
    'L-756/ CC756',
    'L-757/ CC757',
    'L-760/ CC760',
    'L-763/ CC763',
    'L-764/ CC764',
    'L-765/ CC765',
    'L-766/ CC766',
    'L-767/ CC767',
    'L-768/ CC768',
    'L-769/ CC769',
    'L-771/ CC771',
    'L-774/ CC774',
    'L-777/ CC777',
    'L-778/ CC466',
    'L-779 / CC439',
    'L-783/ CC037',
    'L-832/ CC832',
    'L-917/ CC917',
    'L-918/ CC918',
    'L-929/ CC929',
    'L-938/ CC938',
    'L-956/ CC956',
    'L-019/ CC019',
    'L-015/ CC015',
    'L-065/ CC065',
    'L-314/ CC249',
    'L-704/ CC010'
  ]
  response: any = []
  constructor(private covid: CovidService) { }

  ngOnInit() {

  }

  getData() {
    this.covid.getAnswers(this.data).then(success => {
      console.log(success);
      this.response = success;
    }).catch(error => {
      console.error(error);

    })
  }


  search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      map(term => term.length < 2 ? []
        : this.areas.filter(v => v.toLowerCase().indexOf(term.toLowerCase()) > -1).slice(0, 10))
    )

  searchLines = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      map(term => term.length < 2 ? []
        : this.lines.filter(v => v.toLowerCase().indexOf(term.toLowerCase()) > -1).slice(0, 10))
    )

  exportToExcel() {
    const ws: xlsx.WorkSheet =
      xlsx.utils.table_to_sheet(this.epltable.nativeElement);
    const wb: xlsx.WorkBook = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(wb, ws, 'Sheet1');
    xlsx.writeFile(wb, 'covid_survery.xlsx');
  }


}
